color.rgb = mix(color.rgb, vec3(0.0), 0.65);

beginTextM(8, vec2(6, 10));
    text.fgCol = vec4(1.0, 0.0, 0.0, 1.0);
    printString((_I, _m, _p, _o, _r, _t, _a, _n, _t, _space, _E, _r, _r, _o, _r, _exclm));
    printLine();
endText(color.rgb);
beginTextM(4, vec2(15, 36));
    text.fgCol = vec4(1.0, 1.0, 1.0, 1.0);
    printString((_T, _h, _e, _space, _E, _n, _d, _space, _P, _o, _r, _t, _a, _l, _space, _R, _a, _y, _s, _space, _a, _r, _e, _space, _n, _o, _t, _space, _s, _u, _p, _p, _o, _r, _t, _e, _d, _space));
    printLine();
    printString((_o, _n, _space, _A, _p, _p, _l, _e, _space, _d, _e, _v, _i, _c, _e, _s, _dot));
    printLine();
    printLine();
    printString((_D, _i, _s, _a, _b, _l, _e, _space, _i, _t, _space, _u, _n, _d, _e, _r, _colon));
    printLine();
    printString((_E, _S, _C, _space, _gt, _space, _O, _p, _t, _i, _o, _n, _s, _space, _gt, _space, _V, _i, _d, _e, _o, _space, _S, _e, _t, _t, _i, _n, _g, _s, _space, _gt, _space, _S, _h, _a, _d, _e, _r, _space, _S, _e, _t, _t, _i, _n, _g, _s));
    printLine();
    printString((_E, _u, _p, _h, _o, _r, _i, _a, _space, _P, _a, _t, _c, _h, _e, _s, _space, _S, _e, _t, _t, _i, _n, _g, _s, _space, _gt, _space, _P, _o, _p, _u, _l, _a, _r, _space, _S, _e, _t, _t, _i, _n, _g, _s));
    printLine();
    printString((_gt, _space, _E, _n, _d, _space, _P, _o, _r, _t, _a, _l, _space, _R, _a, _y, _s));
    printLine();
endText(color.rgb);
beginTextM(2, vec2(30, 190));
    text.fgCol = vec4(0.8, 0.8, 0.8, 1.0);
    printString((_P, _l, _e, _a, _s, _e, _space, _n, _o, _t, _e, _space, _t, _h, _a, _t, _space, _u, _s, _i, _n, _g, _space, _a, _n, _space, _o, _l, _d, _space, _I, _r, _i, _s, _space, _v, _e, _r, _s, _i, _o, _n, _space, _w, _i, _l, _l, _space, _n, _o, _t));
    printLine();
    printString((_w, _o, _r, _k, _space, _a, _n, _d, _space, _m, _a, _y, _space, _s, _t, _i, _l, _l, _space, _c, _a, _u, _s, _e, _space, _t, _h, _i, _s, _space, _e, _r, _r, _o, _r, _space, _t, _o, _space, _a, _p, _p, _e, _a, _r, _dot));
    printLine();
endText(color.rgb);