animation = min(starter * 0.3, 0.1) * 10.0;
beginTextM(2, vec2(510, 413));
    text.bgCol = vec4(0.0, 0.0, 0.0, 0.5);
    text.fgCol = vec4(1.0, 0.0, 1.0, 1.0);
    printString((_N, _e, _w, _space, _E, _u, _p, _h, _o, _r, _i, _a, _space, _P, _a, _t, _c, _h, _e, _s, _space, _U, _p, _d, _a, _t, _e, _colon));
    text.fgCol = vec4(1.0, 0.0, 0.0, 1.0);
    printString((CURRENT_EUPHORIA_PATCHES_VERSION));
    text.fgCol = vec4(1.0, 1.0, 1.0, 1.0);
    printString((_space, _minus, _gt, _space));
    text.fgCol = vec4(0.0, 1.0, 0.0, 1.0);
    printString((NEXT_EUPHORIA_PATCHES_VERSION));
    printLine();
    text.fgCol = vec4(1.0, 1.0, 1.0, 1.0);
    printString((_D, _o, _w, _n, _l, _o, _a, _d, _colon, _space, _e, _u, _p, _h, _o, _r, _i, _a, _p, _a, _t, _c, _h, _e, _s, _dot, _c, _o, _m, _slash, _d, _o, _w, _n, _l, _o, _a, _d));
    printLine();
    vec3 textColor = color.rgb;
endText(textColor);
color.rgb = mix(textColor, color.rgb, animation);