color.rgb = mix(color.rgb, vec3(0.0), 0.65);
beginTextM(8, vec2(6, 10));
    text.fgCol = vec4(1.0, 0.0, 0.0, 1.0);
    printString((_I, _m, _p, _o, _r, _t, _a, _n, _t, _space, _E, _r, _r, _o, _r));
    printLine();
endText(color.rgb);
beginTextM(4, vec2(15, 36));
    printString((_A, _d, _v, _a, _n, _c, _e, _d, _space, _C, _o, _l, _o, _r, _e, _d, _space, _L, _i, _g, _h, _t, _i, _n, _g, _space, _n, _e, _e, _d, _s, _space, _R, _e, _a, _l, _minus, _T, _i, _m, _e, _space, _S, _h, _a, _d, _o, _w, _s));
    printLine();
    printString((_t, _o, _space, _b, _e, _space, _e, _n, _a, _b, _l, _e, _d, _exclm));
    printLine();
    printLine();
    printString((_P, _l, _e, _a, _s, _e, _space, _e, _n, _a, _b, _l, _e, _space, _R, _e, _a, _l, _minus, _T, _i, _m, _e, _space, _S, _h, _a, _d, _o, _w, _s, _space, _o, _r, _space, _d, _i, _s, _a, _b, _l, _e));
    printLine();
    printString((_A, _d, _v, _a, _n, _c, _e, _d, _space, _C, _o, _l, _o, _r, _e, _d, _space, _L, _i, _g, _h, _t, _i, _n, _g, _space, _a, _t, _colon));
    printLine();
    printString((_S, _h, _a, _d, _e, _r, _space, _S, _e, _t, _t, _i, _n, _g, _s, _space, _gt, _space, _P, _e, _r, _f, _o, _r, _m, _a, _n, _c, _e));
    printLine();
endText(color.rgb);