color.rgb = mix(color.rgb, vec3(0.0), 0.65);
beginTextM(4, vec2(30, 30));
    text.fgCol = vec4(1.0, 0.0, 0.0, 1.0);
    printString((_I, _m, _p, _o, _r, _t, _a, _n, _t, _space, _E, _r, _r, _o, _r));
    printLine();
endText(color.rgb);
beginTextM(4, vec2(30, 50));
    text.fgCol = vec4(1.0, 1.0, 1.0, 1.0);
    printString((_E, _u, _p, _h, _o, _r, _i, _a, _space, _C, _o, _l, _o, _r, _e, _d, _space, _L, _i, _g, _h, _t, _i, _n, _g, _space, _opprn, _S, _c, _r, _e, _e, _n, _s, _p, _a, _c, _e, _clprn));
    printLine();
    printString((_d, _o, _e, _s, _space, _n, _o, _t, _space, _w, _o, _r, _k, _space, _b, _e, _l, _o, _w, _space, _1, _dot, _1, _6, _dot, _4));
    printLine();
endText(color.rgb);
beginTextM(4, vec2(30, 70));
    text.fgCol = vec4(1.0, 1.0, 1.0, 1.0);
    printString((_D, _i, _s, _a, _b, _l, _e, _space, _i, _t, _space, _i, _n, _space, _E, _u, _p, _h, _o, _r, _i, _a, _space, _P, _a, _t, _c, _h, _e, _s, _space, _S, _e, _t, _t, _i, _n, _g, _s, _space, _gt));
    printLine();
    printString((_P, _o, _p, _u, _l, _a, _r, _space, _S, _e, _t, _t, _i, _n, _g, _s, _space, _gt, _space, _E, _u, _p, _h, _o, _r, _i, _a, _space, _C, _o, _l, _o, _r, _e, _d, _space, _L, _i, _g, _h, _t, _i, _n, _g));
    printLine();
endText(color.rgb);