#Define the initial thread count number of threads
#If the value is 6, new worlds will start with 6 thread counts as a initial value
#This is useful for modpacks with dimensional mods, instead of fallback on default's 3 you can configure how many can use
#ADVICE: Gamerule and this config is capped to max available processors of the server
#if you set the value above available processors, forge will set it back to defaults 3
#This was done to prevent users gameplay got slowed by not having enough threads
#Range: 2 ~ 20
default_gamerule_threads = 3
#WARNING: very VERY EXPERIMENTAL, do not use it (except if you want world corruption)
#This feature is intended to ignore crashes ticking levels, for the good sake of not have to restart your entire server
#Have i mentioned IS EXPERIMENTAL?
ignore_tick_crash = false

