modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="hive_ad_prog"
version="1.0.0"
displayName="Hive_AD_prog"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="User, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hive_ad_prog]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration